### ISSUE TITLE
GPU memory failure

### ISSUE THREAD

**Issue by SpecificOcean146** [radarsimx/radarsimpy#10]
Hello!

   Thank you for posting this incredibly helpful code.

   I am attempting to run your example "RCS of a corner reflector" to generate a RCS vs. frequency graph, using your latest v11.1 py3.10 CUDA build. I am using your example code verbatim, except for different .stl models. I seem to be hitting a GPU memory limit that causes a crash, shown below. I'm using a RTX3070ti so memory should not be an issue. Do you have any idea how to resolve this issue? Thank you again!

![image](https://github.com/radarsimx/radarsimpy/assets/29168539/af6885a9-327a-4448-b6e2-5b8372e5204c)

**Comment by rookiepeng** [comment]
It is likely the model is too large and the simulator tries to launch too many rays.

.stl model doesn't include unit for the model, and the simulator treat it as meters by default. If your model is using millimeter, it will be 1000x of it actual size in the simulator.

**Comment by SpecificOcean146** [comment]
Thank you for the reply.

This is probably the correct explanation. I am using an .stl model that is pretty large, roughly 16 meters long. I assume the simulator is interpreting the scale correctly in my case since the Meshio figure of my model looks correct. It is just a large model. I can run the simulation successfully with this large model if I decrease the Ray Density from 10 to 4. Does the model accept other files besides .stl?

I might try to restructure the frequency index loop (1Ghz to 79Ghz) of the example code so that it offloads some of the memory from the GPU at each iteration, but I have no idea if that's possible without digging further.

Thank you again for taking the time to reply and for creating and maintaining this code. I have had a lot of fun learning python and radar principles while using it.

**Comment by rookiepeng** [comment]
It supports .obj but requires PyMeshLab

I am planning to add a feature to serialize the processing then the ray size is too large.
