### ISSUE TITLE
The "CMakeLists.txt" file is missing and thus cannot build "radarsimpy" using CMake.

### ISSUE THREAD

**Issue by RadetzkyLi** [radarsimx/radarsimpy#12]
I want to try this project, but according to the examples of jupyter notebook, I found I must build the directory "radarsimpy" first. In windows, this is down by running "build_win.bat". By adding pause, I found the running failed when encountering the following command:
    **_cmake cmake -DGTEST=ON .._**
By searching on Google, it reveals that the missing "CMakeLists.txt" leaded to this problem. According to "build_win.bat", the file shoud locate in "/src/radarsimc/".
So, can you please add "CMakeLists.txt" to such directory? Or if I were wrong, what should I do if I want to use this project.

**Comment by rookiepeng** [comment]
Building radarsimpy requires radarsimc, which is not open source. Please download the compiled module from: https://radarsimx.com/product/radarsimpy/
