### ISSUE TITLE
Pulsed Coherent Radar

### ISSUE THREAD

**Issue by campbellyoung** [radarsimx/radarsimpy#13]
I'm wanting to simulate a pulsed coherent radar (specifically Acconeer A111) which operates at 60 GHz over short distances (e.g. 2m). The best physical description I can find is https://docs.acconeer.com/en/latest/handbook/a111/system_overview.html

I've tried modifying your cfar example to work at higher frequencies and shorter distances, but haven't had much luck. 

If you could point me in the right direction for sensible radar settings that'd be great, or if PCR radars aren't supported that'd be good to know too.

Sorry for the dumb question, I am relatively new to physical radar parameters as I typically use Acconeer's SDK which configures things with profiles, which as far as I can tell just changes the length of each pulse.

**Comment by rookiepeng** [comment]
pulsed radar is not supported.
