### ISSUE TITLE
Is target permittivity used? 

### ISSUE THREAD

**Issue by SpecificOcean146** [radarsimx/radarsimpy#14]
In the example "FMCW Radar with a Car" one of the targets has a "permittivity" and "is_ground" parameter. Is permittivity of the object actually factored in the calculation, or is this just a placeholder? Digging into the functions, it does not look to me like the "permittivity" parameter is actually passed on. I would like to use a target's permittivity to calculate a more accurate RCS but I am not sure if this is actually possible.

**Comment by rookiepeng** [comment]
Yes, the permittivity is used.
