### ISSUE TITLE
Is RadarSimC not open sourced?

### ISSUE THREAD

**Issue by rzy0901** [radarsimx/radarsimpy#15]
I just saw there is a dependent repository  in [src folder](https://github.com/radarsimx/radarsimpy/tree/master/src).
Just wonder if i can have access to this C++ source codes.
![image](https://github.com/radarsimx/radarsimpy/assets/66763689/d7b6bbcf-725b-4e5f-aad2-63801e95a8ef)

**Comment by rookiepeng** [comment]
No
