### ISSUE TITLE
Using permittivity in RCS calculation

### ISSUE THREAD

**Issue by SpecificOcean146** [radarsimx/radarsimpy#17]
Is it possible to use the permittivity parameter in RCS calculation? Looks like permittivity is defined and used in other functions, but not RCS. This would be a helpful feature as RCS is a function of the target material. What are the default object reflection characteristics in the shooting bouncing ray RCS calculations?

Thank you

**Comment by rookiepeng** [comment]
RCS calculation is treating everything as PEC now.

**Comment by SpecificOcean146** [comment]
Thank you, good to know. Thanks for adding the enhancement too.

**Comment by rookiepeng** [comment]
Please leave it open. I will close it when it's done.
