### ISSUE TITLE
Can it be applied to the pulse radar simulation？

### ISSUE THREAD

**Issue by suoyongfeng** [radarsimx/radarsimpy#23]
I wanna if it is possible to apply to simulate pulse radar, such as marine navigation PPI radar.
If true, how to set up the radar parameters?

**Comment by suoyongfeng** [comment]
Similar to the output that this Matlab program can achieve：

https://ww2.mathworks.cn/help/radar/ug/simulate-maritime-radar-ppi.html

**Comment by rookiepeng** [comment]
This is out of the scope of radarsimpy
