### ISSUE TITLE
GPU build for Python 3.10

### ISSUE THREAD

**Issue by Ockhius** [radarsimx/radarsimpy#24]
Is it possible to build CUDA enabled GPU builds for python 3.10? Unfortunately, only 3.11 supported currently.

I intend to use this tool in conjunction with Blender 3.4 which comes with Python 3.10.

**Comment by rookiepeng** [comment]
You can move to Blender 3.5. This is my part time project and I have very limited resource to support it. I can't satisfy all the requests on different variants.
