### ISSUE TITLE
Non-idealized (Noisy) Radiation Patterns 

### ISSUE THREAD

**Issue by Ockhius** [radarsimx/radarsimpy#28]
When I used non-idealized radiation patterns resulting FFT of the IQ data seems wrong.

I use following radiation patterns, idealized ones gives correct fft while others fft is just noise. 

Is this a bug in simc? In real patterns angles are not regularly spaced. I can also reproduce by adding Gaussian noise to ideal radiation patterns.

![newplot(9)](https://github.com/radarsimx/radarsimpy/assets/12793502/35ecc665-2427-45c5-abc7-8dfff9171a81)
![newplot(11)](https://github.com/radarsimx/radarsimpy/assets/12793502/12c0b7ba-7b44-4d02-be72-a175dcc5b05f)
![newplot(10)](https://github.com/radarsimx/radarsimpy/assets/12793502/ecc3848d-62c4-42d3-9aab-234e4ff1f336)

**Comment by rookiepeng** [comment]
Could you try re-sample the real patterns with equally spaced angles?

**Comment by rookiepeng** [comment]
Close due to no updates
