### ISSUE TITLE
how can i get the radarsimcpp?

### ISSUE THREAD

**Issue by friendlyCamel** [radarsimx/radarsimpy#31]
hello! i check the ./src and can't get the radarsimcpp, an '404 not found' appeared haha. i would like to use this repo to generate FMCW
 signal and then feed my neural network, but i am not sure how an object maybe a human mesh was "scanned"  by the virtual radar, thanks if i can get your help! Wish you good luck~

**Comment by rookiepeng** [comment]
please use the pre-built version: https://radarsimx.com/product/radarsimpy/
