### ISSUE TITLE
Polarization coordinate frame and notations

### ISSUE THREAD

**Issue by yuriled** [radarsimx/radarsimpy#38]
Hello Dr. Peng,

Was not able to find this information in documentation.

Antenna polarization [x, y, z]. default = [0, 0, 1] (vertical polarization)

Guess 'x' is normal to antenna surface and in line with direction of wave propagation.

How can one set circular polarization, if that is possible? Furthermore, RHCP and LHCP?

Thank you.

**Comment by rookiepeng** [comment]
For circular polarization, you can set [0, -1j, 1] or [0, 1j, 1]

**Comment by yuriled** [comment]
Well noted with thanks!
