### ISSUE TITLE
radarsimcpp missing

### ISSUE THREAD

**Issue by telearis** [radarsimx/radarsimpy#40]
Hello,

It seems that radarsimcpp (used via git submodules) is missing.

This repository does not exist or is not accessible:
[https://github.com/rookiepeng/radarsimcpp](https://github.com/rookiepeng/radarsimcpp)

**Comment by rookiepeng** [comment]
https://github.com/radarsimx/radarsimpy?tab=readme-ov-file#build

Building radarsimpy requires to access the source code of radarsimcpp. If you don't have access to radarsimcpp, please use the [pre-built module](https://radarsimx.com/product/radarsimpy/).

**Comment by telearis** [comment]
Does that mean, radarsimcpp is closed source?

That would be unfortunate since, on Linux you compile against some glibc which might not be the one on the user's host.

**Comment by rookiepeng** [comment]
You are correct, radarsimcpp is closed source. I am relying on GitHub free action runners and my personal computer to compile the code. It is not feasible for me to support too many versions of the OS.

**Comment by telearis** [comment]
Thank you for the answer!
Then, it seems we will not be able to use radarsimpy at our research group.

Thanks again and good luck!
