### ISSUE TITLE
radarsimpy-GPU version Ubuntu dependency

### ISSUE THREAD

**Issue by yigitee** [radarsimx/radarsimpy#42]
When I download the GPU version of radarsimpy 12.3.2, I get the following error: ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found. After some search, i found out that GLBC_2.35 is not available in Ubuntu 20.04. If there is a way to use GPU support in Ubuntu 20.04, can you help? If not, perhaps you should add Ubuntu dependency in GPU support.

**Comment by rookiepeng** [comment]
Hi, I don't have a machine with Ubuntu 20, the current module is only built on Ubuntu 22. I will add this dependence into the instruction.
