### ISSUE TITLE
Update pre-built module to 12.4

### ISSUE THREAD

**Issue by robotron5exe** [radarsimx/radarsimpy#45]
Hi @rookiepeng ,
could you please update pre-built module to 12.4. (https://radarsimx.com/product/radarsimpy/)

Best regards.

**Comment by rookiepeng** [comment]
Hi, I am still doing some tests on this version. I will upload it once it is ready

**Comment by rookiepeng** [comment]
v12.4.0 is available on https://radarsimx.com/product/radarsimpy/

**Comment by robotron5exe** [comment]
Thanks for the quick response!
