### ISSUE TITLE
missing simulator imports 

### ISSUE THREAD

**Issue by newradar1** [radarsimx/radarsimpy#46]
When I try to run example codes ( in this case aoa.py) I run into the initial import errors such as module not found due to these: 
from radarsimpy.simulator import sim_radar
from radarsimpy.rt import rcs_sbr

My directory structure is this: 
![image](https://github.com/user-attachments/assets/2914165a-430c-48c9-ad0e-477ac45bbc59)

Please could you help me fix the sources

**Comment by rookiepeng** [comment]
please post the error message
