### ISSUE TITLE
Insight into how simulator models noise

### ISSUE THREAD

**Issue by kbali1297** [radarsimx/radarsimpy#49]
I was working with pulse doppler radar example and wanted to find ways to detect the signal even in case of high noise.
Is it possible to know how the noise is modeled in the simulator (especially the pulse doppler simulation example)?

Insights as to which distribution the noise belongs to and ways of filtering it to extract signal would be highly appreciated.

```
data = sim_radar(radar, targets)
baseband = data["baseband"] + data["noise"]
```
In the example below I have plotted the IQ and Amplitude signals to extract information as to which location the object is located (6830 m here).
![06830_11actual](https://github.com/user-attachments/assets/caded001-79ba-4825-b336-85042ac037ca)

**Comment by rookiepeng** [comment]
noise generation is a part of radarsimpy, not in the closed source radarsimcpp. You can find the source code of noise generation at: https://github.com/radarsimx/radarsimpy/blob/master/src/radarsimpy/simulator.pyx#L381

The amplitude of the noise is calculate at: https://github.com/radarsimx/radarsimpy/blob/master/src/radarsimpy/radar.py#L452

**Comment by kbali1297** [comment]
Thank you very much for pointing these out. I presume the noise is just random numpy array with elements according to a normal distribution.

**Comment by rookiepeng** [comment]
Yes, you are correct
