### ISSUE TITLE
Weird Shape of Return Signal Phase Angle

### ISSUE THREAD

**Issue by unexcellent** [radarsimx/radarsimpy#50]
Hey there, 

first of all, I really appreciate your framework. It is one of the best out there for simulating radar.

While playing around with the parameters of the [pulsed radar example](https://radarsimx.com/2024/09/13/pulsed-radar/), I encountered a return signal shape, that I can not explain.

If the velocity of the target is increased in the x-direction, a linear shift in the phase angle of the return signal should be expected. And although the phase angle shows a shift in the return signal of `sim_radar()`, it has a "blocky" or "staircase-like" shape.
<img width="1364" alt="image" src="https://github.com/user-attachments/assets/ab13da6a-e3fa-4752-a0a6-112384debc39">

From my physical understanding of the radar domain, this should produce a purely linear signal.
Did I miss something or is this an issue in the `radarsimx` package?

This is the code that produced the plot:

```python
from radarsimpy import Radar, Receiver, Transmitter
import plotly.graph_objs as go
from scipy import constants
from radarsimpy.simulator import sim_radar
import numpy as np

antenna_gain = 20  # dBi

az_angle = np.arange(-20, 21, 1)
az_pattern = 20 * np.log10(np.cos(az_angle / 180 * np.pi) ** 500) + antenna_gain

el_angle = np.arange(-20, 21, 1)
el_pattern = 20 * np.log10((np.cos(el_angle / 180 * np.pi)) ** 400) + antenna_gain

light_speed = constants.c

max_range = 5000  # Maximum unambiguous range
range_res = 500  # Required range resolution
pulse_bw = light_speed / (2 * range_res)  # Pulse bandwidth
pulse_width = 1 / pulse_bw  # Pulse width
prf = light_speed / (2 * max_range)  # Pulse repetition frequency
prp = 1 / prf
fs = 64e6  # Sampling rate 6 msps
fc = 35e9  # Carrier frequency
num_pulse = 1

total_samples = int(prp * num_pulse * fs)
sample_per_pulse = int(total_samples / num_pulse)

mod_t = np.arange(0, total_samples) / fs  # Time series of the modulation
amp = np.zeros_like(mod_t)  # Amplitude of the modulation
amp[mod_t <= pulse_width] = 1  # Create a rectangular pulse

tx_channel = dict(
    location=(0, 0, 0),
    azimuth_angle=az_angle,
    azimuth_pattern=az_pattern,
    elevation_angle=el_angle,
    elevation_pattern=el_pattern,
    amp=amp,
    mod_t=mod_t,
)

tx = Transmitter(
    f=fc,
    t=1 / prf,
    tx_power=67,  # dBm
    pulses=num_pulse,
    channels=[tx_channel],
)

rx_channel = dict(
    location=(0, 0, 0),
    azimuth_angle=az_angle,
    azimuth_pattern=az_pattern,
    elevation_angle=el_angle,
    elevation_pattern=el_pattern,
)

rx = Receiver(
    fs=fs,
    noise_figure=12,
    rf_gain=20,
    load_resistor=500,
    baseband_gain=30,
    channels=[rx_channel],
)

radar = Radar(transmitter=tx, receiver=rx)

target = dict(location=(1000, 0, 0), speed=(150, 0, 0), rcs=10, phase=0)

data = sim_radar(radar, [target])
timestamp = data["timestamp"]
baseband = data["baseband"]  # noise is left out on purpose

fig = go.Figure()
fig.add_trace(
    go.Scatter(
        x=timestamp[0, 0, :],
        y=np.arctan2(np.real(baseband[0, 0, :]), np.imag(baseband[0, 0, :])),
        name="Angle",
    )
)
fig.update_layout(
    yaxis=dict(title="Angle (rad)"),
    xaxis=dict(title="Time (s)"),
    template="plotly_dark",
)
fig.show()
```

**Comment by rookiepeng** [comment]
Hello,
Thank you for providing this example! This seems to be a precision issue. To improve the performance, I am using single precision float in some of the calculations. Looks like I need to use double precision. I will try something and come back to you later.

**Comment by rookiepeng** [comment]
I get this plot after using double precision float for all the internal calculations. I will incorporate the fix in the next release. Thanks again for reporting this issue.
![image](https://github.com/user-attachments/assets/51d85815-1dab-4796-a222-8cc547956e7d)

**Comment by unexcellent** [comment]
Thanks a lot or quickly fixing it. Since I got radarsimpy through the donation, I do not have access to the new release. Is there a way for me to get the newest version without spending money again?

**Comment by rookiepeng** [comment]
We can share you a coupon to download the new release when it is available. Could you please send me an email (info@radarsimx.com) so that I can share it with you?
